### ISSUE TITLE
Exclude certain classes

### ISSUE THREAD

**Issue by TimvdLippe** [manoelcampos/javadoc-coverage#2]
Not sure if I missed it, but I couldnt find it in the readme nor in the code. We have several internal packages where javadoc is not required. But our public API does require it. Could you add an option to exclude classes based on a regex?

**Comment by manoelcampos** [comment]
Of course. It will be a nice feature.
Thanks for reporting.

**Comment by manoelcampos** [comment]
Hello @TimvdLippe,
I've just realized that this could be done by the maven-javadoc-plugin, as detailed in this [link](https://maven.apache.org/plugins/maven-javadoc-plugin/examples/exclude-package-names.html) already.

You can try this using the sample-project provided. For instance, you can add
`<excludePackageNames>com.manoelcampos.sample2</excludePackageNames>` into the `<configuration>` tag of the second `<execution>` tag of the maven-javadoc-plugin.
This way, the generation of regular javadoc HTML pages will cover all files, while the coverage plugin will exclude the package `com.manoelcampos.sample2`.

The complete plugin configuration is shown below:

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-javadoc-plugin</artifactId>
    <version>2.10.4</version>
    <configuration>
        <encoding>UTF-8</encoding>
    </configuration>
    <executions>
        <!-- Exports JavaDocs to regular HTML files -->
        <execution>
            <id>javadoc-html</id>
            <phase>package</phase>
            <goals>
                <goal>javadoc</goal>
            </goals>
        </execution>

        <!-- Generates the JavaDoc coverage report -->
        <execution>
            <id>javadoc-coverage</id>
            <phase>package</phase>
            <goals>
                <goal>javadoc</goal>
            </goals>
            <configuration>
                <doclet>com.manoelcampos.javadoc.coverage.CoverageDoclet</doclet>
                <docletArtifact>
                    <groupId>com.manoelcampos</groupId>
                    <artifactId>javadoc-coverage</artifactId>
                    <version>1.0.0</version>
                </docletArtifact>
                <!-- Exclude packages from the coverage report. -->
                <excludePackageNames>com.manoelcampos.sample2</excludePackageNames>
            </configuration>
        </execution>
    </executions>
</plugin>
```

I've just updated the readme to include the example.

**Comment by TimvdLippe** [comment]
Oh thanks for the link! Could you mention that in the README?

**Comment by manoelcampos** [comment]
I've just updated the readme to include the example.
