### ISSUE TITLE
Use the javadoc-coverage report to be generated under the reporting tag in pom.xml

### ISSUE THREAD

**Issue by subkrish** [manoelcampos/javadoc-coverage#5]
Reports are created from the plugins added under the reporting tag in the `pom.xml` .

I found out that I can't add it under the `reporting` tag in pom.xml because it contains the `execution` tag. I have to put it under the `build` tag and because of that it does not get added to the list of project reports for a project.

The project reports are generated by the plugins placed under the `reporting` tag but I can't put this plugin there.

**Comment by manoelcampos** [comment]
Hello @subkrish,

If you want to include the javadoc-coverage report into your maven site, and also the regular javadoc HTML pages, you have to configure the `reporting` tag like below:

```xml
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>2.10.4</version>
                <reportSets>
                    <reportSet>
                        <!-- Exports JavaDocs to regular HTML files -->
                        <id>javadoc-html</id>
                        <reports>
                            <report>javadoc</report>
                        </reports>
                        <configuration>
                            <encoding>UTF-8</encoding>
                        </configuration>
                    </reportSet>

                    <reportSet>
                        <!-- Generates the JavaDoc coverage report -->
                        <id>javadoc-coverage</id>
                        <reports>
                            <report>javadoc</report>
                        </reports>
                        <configuration>
                            <name>JavaDoc Coverage</name>
                            <description>Percentage of the code coverage by JavaDoc documentation.</description>
                            <encoding>UTF-8</encoding>
                            <doclet>com.manoelcampos.javadoc.coverage.CoverageDoclet</doclet>
                            <docletArtifact>
                                <groupId>com.manoelcampos</groupId>
                                <artifactId>javadoc-coverage</artifactId>
                                <version>1.0.0</version>
                            </docletArtifact>
                            <destDir>javadoc-coverage</destDir>
                            <!-- You can also use -o instead of -outputName to define 
                            the name of the generated report. -->
                            <additionalparam>-outputName "index.html"</additionalparam>
                        </configuration>
                    </reportSet>
                </reportSets>
            </plugin>
        </plugins>
    </reporting>
```

Notice that I'm generating the coverage report into `target/site/javadoc-coverage` and defining the name of the coverage report as index.html.

I think that it's more convenient to have the coverage report with a different name to enable including it inside the javadoc site (as it's performed by the sample-project). However, using the reporting tag, it doesn't allow me to generate two reports into the same directory. It checks that the index.html already exists and doesn't generate the report defined into the second `reportSet` tag. 
But since the maven site expects the report to be called "index.html", the regular JavaDocs HTML and the JavaDocs Coverage Report should be generated into different directories in this case.

The reports section in the generated maven site may look like this.
<img width="1174" alt="screenshot" src="https://user-images.githubusercontent.com/261605/28776355-33f17824-75ee-11e7-8e9c-a6f89ea4b0e9.png">

**Comment by subkrish** [comment]
@manoelcampos Could this behavior be added because all the reports for the Checkstyle project are added through this way? I think that it is the only way the plugin would be approved in the project to be used as.

Also as you have mentioned above, the location pointed by the site generated by Maven is empty for the javadoc-coverage. I added the plugin and ran a check.

**Comment by manoelcampos** [comment]
Yes, I have to check how to do that. I tried to include a parameter to the javadoc tool, but the tool doesn't accept it. In the worst case, I can hardcode the report name as index.html and always define a different directory for the coverage report.

I'll be available to check this only in 1 or 2 days.

**Comment by subkrish** [comment]
@manoelcampos Please take your time because in the Checkstyle project, the javadoc report can only be added in the way I have mentioned by adding it under `reporting` tag.

**Comment by manoelcampos** [comment]
Hello @subkrish,

I've just closed the issue. The new version 1.1.0 will be available at maven central soon.

Download the sources, try the new version and let me know how it goes.
I updated the pom.xml snippet at the previous message, including the new parameter `-outputName` at the tag `<additionalparam>-outputName "index.html"</additionalparam>`.

Check the complete example above (which has some comments). The readme was accordingly updated too.

Thanks for reporting the issue.

**Comment by subkrish** [comment]
@manoelcampos I tried it but for some reason the file doesn't still seem to exist in the folder. Could you implement it in you sample-project so that I can test it on yours and then add it in the Checkstyle project afterwards?

**Comment by manoelcampos** [comment]
@subkrish Try the project I uploaded to [maven-site branch](https://github.com/manoelcampos/javadoc-coverage/tree/maven-site).

It has the minimal required configuration. The charset properties defined into the pom.xml are optional, but if you remove them, you'll get some warnings. There are other warnings such as "Report plugin org.apache.maven.plugins:maven-project-info-reports-plugin has an empty version.".

If you want to fix this, you can just include the `maven-project-info-reports-plugin` plugin.
Everything is working fine for me. See if your project's configuration is different from mine's and let me know if you need some help.
