### ISSUE TITLE
Wrong Coverage-Percentage computed

### ISSUE THREAD

**Issue by stieglma** [manoelcampos/javadoc-coverage#6]
When having additional tags (e.g. @throws IllegalArgumentException or IllegalStateException without declaring the exception, which is not necessary as it is a runtime exception, we just want to tell the user under which circumstances this can occur) the computed percentage is wrong.

Example class where wrong numbers occur (150% for the constructor):
```Java
public class TestJavadocCoverage {

    /**
     * @param param
     *            unimportant
     * @throws IllegalStateException
     *             unimportant
     */
    public TestJavadocCoverage(int param) {
       // not important
    }
}
```

we used version 1.1.0 from maven central

**Comment by manoelcampos** [comment]
Thanks for reporting. I'll take a look in a few days.

**Comment by manoelcampos** [comment]
Hello @stieglma 
I've just closed this issue. See the commit message for more details.

**Comment by stieglma** [comment]
cool, thanks! does version 1.1.1 on maven central already contain this fix?

**Comment by manoelcampos** [comment]
For sure :D
