### ISSUE TITLE
Bugs in MethodDocStats

### ISSUE THREAD

**Issue by stieglma** [manoelcampos/javadoc-coverage#7]
Hi,

by going through the code I found some suspicious code snippets:
* The method `isReturnValueDocumented` is unused and should be removed
* The method `getDocumentedMembers` returns `0`, and should instead return the number of documented members (extract from `getDocumentedMembersPercent`)
* there is a TODO for the `@return` annotation regarding void methods and constructors, this can easily be integrated, see the sample code below:

```java
    @Override
    public long getDocumentedMembers() {
        int countReturnPartial = 0;
        if (!isVoidMethod() && !doc.isConstructor()) {
            if (Arrays.stream(doc.tags()).filter(t -> t.name().equals("@return")).map(Tag::text).anyMatch(Utils::isNotStringEmpty)) {
                countReturnPartial = 1;
            }
        }
        return Utils.boolToInt(hasDocumentation()) + paramsStats.getDocumentedMembers() + thrownExceptions.getDocumentedMembers()
                + countReturnPartial;
    }

    @Override
    public double getDocumentedMembersPercent() {
        int countReturnTotal = 1;
        if (isVoidMethod() || doc.isConstructor()) {
            countReturnTotal = 0;
        }

        // this 1 is used to count the method as a element which may be documented or not
        return Utils.computePercentage(getDocumentedMembers(), 1 + getMembersNumber() + countReturnTotal);
    }

    private boolean isVoidMethod() {
        return doc.isMethod() && ((MethodDoc) doc).returnType() == null;
    }
```

**Comment by manoelcampos** [comment]
Thanks for reporting the issues. I've made a review and just fixed them. If you run `mvn package` on the sample project, it will be easier to check that for the small `Interface2`. It has currently 22 documentable members. This is the sum of documentable members for it's: fields + each method + 1 (the interface itself).

**Comment by stieglma** [comment]
I found an even more serious bug in the computation of the "overall" percentage values. They are computed bottom-up from the smallest bits (methods and fields in classes, classes and packages in javadocsstats) and everywhere happens only a `mean`. This means that projects without `package-info.java` files will never have more than 50% coverage, although there is only a tiny bit missing. For the overall coverages all contained numbers need to be used instead of the percentages computed out of them.

**Comment by manoelcampos** [comment]
If I correctly understood your point, the issue is just with the "Project Documentation Coverage" computed at the last line of the table. Isn't it?

**Comment by stieglma** [comment]
I am not quite sure there, but at least the Project Documentation Coverage is wrong, at first it uses only package javadoc and class javadoc (methods and members are ignored completely) and at second the absolute numbers should be added before computing the percentage to have a better overall view of the javadoc-coverage

**Comment by manoelcampos** [comment]
For classes and interfaces, all the values are being summed up to compute the first row for these elements. I just have to check the "Classes/Interfaces/Enums" line which may have the same issue as the last line.

I've just updated the project to make table header to sticky at the top of the page. This way, it will be easier to check long tables.

I appreciate if you could give me a feedback about the issue #9. I think it's fine that way. And about issue #8, please merge the current changes into your fork.

Thanks again.
